docs: Add Korean README translation
One-Language/One pull request #383
Opened 2022-09-07 18:10 UTC by Yaminyam

2022-09-07 18:46 UTC, BaseMax commented
Wow!
Thanks, I don't know Korean but It seems several texts are not translated. such as Titles

Would you please take a look again and make sure almost everything possibility has been translated?

2022-09-07 18:47 UTC, BaseMax commented
```
<h2 id="table-of-contents">Table of Contents</h2>
<details open="open">
  <ol>
    <li><a href="#features-of-one">Features of <b>One</b></a></li>
    <li><a href="#roadmap">RoadMap</a></li>
    <li><a href="#code-examples">Code Examples</a></li>
    <li><a href="#getting-started">Getting Started</a></li>
    <li><a href="#get-involved">Get Involved</a></li>
    <li><a href="#license">License</a></li>
  </ol>
</details>


<h2 id="features-of-one">➤ Features of One</h2>

<h2 id="roadmap">➤ RoadMap</h2>

<h2 id="code-examples">➤ Code Examples</h2>

**Convert to C:**


**Another draft:**

**Another draft:**


### Old CLI Development


### Old GUI Development: (Web, Software)


<h2 id="getting-started">➤ Getting Started</h2>


#### Supported Environments

- [x] GNU / Linux <!--which Linux?-->
- [x] Windows
- [ ] macOS (Not complete)
- [ ] BSD
```

2022-09-07 18:47 UTC, BaseMax commented
```
# The One Programming Language 💚 💙 🧡 🤍 💖 🖤


### Compiler for the One Language will be released in a few months
```

2022-09-08 05:49 UTC, jbampton commented on langs/READMD_KR.md
> +<!-- prettier-ignore-end -->
We only have this button on the English README

```suggestion
```

2022-09-08 05:49 UTC, jbampton commented on langs/READMD_KR.md
> +## Contributors ✨
We don't need this "Contributors" section.  Only on the English README

2022-09-08 10:34 UTC, BaseMax commented
Thank you for the review.

2022-09-14 11:30 UTC, jbampton requested changes
We have some broken links

2022-09-14 16:03 UTC, BaseMax commented
Thanks

2022-09-15 07:35 UTC, jbampton requested changes
So you will need a link for the Korean README in the language links on each README

2022-09-16 04:52 UTC, jbampton commented on langs/READMD_KR.md
> +[한국어](README_KR.md)
```suggestion
[한국어](README_KR.md)
&nbsp;
[русский](README_RU.md)
&nbsp;
[Türkçe](README_TR.md)
&nbsp;
[Українська](README_UK.md)
```

2022-09-16 07:36 UTC, BaseMax commented
Thanks, John please speed up processing this PR.

2022-09-16 07:48 UTC, jbampton commented on langs/READMD_KR.md
> +[sponsorbadge]: https://camo.githubusercontent.com/da8bc40db5ed31e4b12660245535b5db67aa03ce/68747470733a2f2f696d672e736869656c64732e696f2f7374617469632f76313f6c6162656c3d53706f6e736f72266d65737361676
```suggestion
```

2022-09-16 07:52 UTC, jbampton requested changes
The `langs` folder is now `docs`.

Could you please update ?

2022-09-16 08:07 UTC, jbampton requested changes
The Korean README filename is misspelt

Also you will need a link to the Korean README on the main English README

2022-09-16 08:11 UTC, BaseMax approved these changes
Thanks

2022-09-16 08:30 UTC, Yaminyam commented
> The Korean README filename is misspelt
> 
> Also you will need a link to the Korean README on the main English README

Do I have to set the file name to ko, which kr doesn't want?

2022-09-16 08:33 UTC, jbampton commented
You have used `READMD_KR.md` 

Should be `README_KR.md`

2022-09-16 11:14 UTC, BaseMax approved these changes
Thanks for fix.

2022-09-16 11:15 UTC, jbampton approved these changes
Well done. Thanks 💯

2022-09-16 11:17 UTC, merged

2022-09-16 11:21 UTC, BaseMax commented
Again thanks @Yaminyam.
You are welcome to add yourself to Next Community. https://github.com/NextCommunity/NextCommunity.github.io#do-you-want-to-add-yourself