Use lowercase HTTP header field names to be compatible with HTTP/2
One-Language/One pull request #425
Opened 2022-12-22 15:56 UTC by jbampton

"Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion. However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2. A request or response containing uppercase header field names MUST be treated as malformed (Section 8.1.2.6)."

https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2

https://web.dev/performance-http2/

2022-12-22 16:00 UTC, BaseMax requested changes
`HTTP-type` is not a standard header. The valid header is `HTTP/1.0 404 Not Found`.

2022-12-22 16:08 UTC, jbampton commented
But to be consistent with the spec we should use lowercase header field names and to make our own code standardized it would be good to have all HTTP header field names lowercase even if they are non-standard headers

2022-12-25 16:04 UTC, jbampton commented
Hey @BaseMax ready for review now 👍

2022-12-25 16:24 UTC, BaseMax approved these changes
LGTM

2022-12-25 16:25 UTC, merged